### ISSUE TITLE
Issue writing videos to a docker volume mapped to a NFS share

### ISSUE THREAD

**Issue by psychowood** [pducharme/UniFi-Video-Controller#114]
This is the error i get:

<img width="697" alt="image" src="https://user-images.githubusercontent.com/115389/47283173-6c3c0c80-d5e2-11e8-8fd6-7d9c5d9f3c87.png">

I tried mapping the _videos_ path inside or outside the data folder, without any difference. The data volume is mapped correctly with r/w capabilities, on the very same NFS share, but when I try to change the recording settings i get 

`ERROR  rejectIfPathInvalid - ERROR: Incorrect Ownership /usr/lib/unifi-video/data/videos:nobody in tomcat-HTTP-exec-4`

This is the run command:

`docker run -d --name unifi-video --restart="always" --net=homenet --ip=192.168.1.5  --cap-add SYS_ADMIN --cap-add DAC_READ_SEARCH -v /mnt/import/unifi-video/config:/var/lib/unifi-video -v /mnt/import/unifi-video/videos:/var/lib/unifi-video/videos -e TZ=Europe/Rome -e PUID=65534 -e PGID=65534 -e DEBUG=1 pducharme/unifi-video-controller:latest`

Because of the NFS share, mounted with the squash option, I'm trying to run unifi video as nobody, and this is what I see as running processes:

<img width="1358" alt="image" src="https://user-images.githubusercontent.com/115389/47284796-f1c2bb00-d5e8-11e8-986a-bde1820efdb3.png">

Is it normal to have two unifi-video commands, one owned my root and one owned by nobody?

Thanks

**Comment by fryfrog** [comment]
What user/group is `65534`? Your NFS share will need to be owned by that user/group ID and have r/w permissions for that UID/GID.

And yes, it fires some stuff up as root and then drops to the user specified. :(

**Comment by psychowood** [comment]
65534 is the UID/GID for nobody/nogroup, correctly mapped by the NFS share with the squash_all,root_squash options. If I bash in the container I can see the mount owned by nobody.

I've found a [discussion](https://community.ubnt.com/t5/UniFi-Video/Issue-writing-to-NFS-on-new-Install-3-8-2/td-p/2110523) in the ubnt forum, it seems to be some sort of incompatibility with the nobody user, which I was hoping was solved with the PUID/PGID options...

**Comment by fryfrog** [comment]
Ah, I wouldn't have guessed that. Personally, I just run it as `unifi-video` user and group. On the inside, I'm pretty sure it *is* still running as `nobody`, but on the outside the UID/GID would be something else. Try something like that?

**Comment by Beaving** [comment]
I have had a lot of issues with permissions related this Docker and NFS mounts. In the end I fixed it. Here is the command I use:

docker run \
-d \
--name unifivideo \
--cap-add SYS_ADMIN \
--cap-add DAC_READ_SEARCH \
-p 1935:1935 \
-p 6666:6666 \
-p 7080:7080 \
-p 7442:7442 \
-p 7443:7443 \
-p 7444:7444 \
-p 7445:7445 \
-p 7446:7446 \
-p 7447:7447 \
-v /media/data/Docker/unifivideo:/var/lib/unifi-video \
-v /media/data/Docker/unifivideo/videos:/videos \
-e TZ=Europe/Berlin \
-e PUID=1000 \
-e PGID=1000 \
-e DEBUG=1 \
--security-opt apparmor:unconfined \
--cpus="1.5" \
pducharme/unifi-video-controller:3.9.11 ; docker exec -it unifivideo /bin/bash -c "chown -R 1000:1000 /videos"
#chown needed, otherwise unifi cant use the folder for videos. this docker does not like to run as root
#needs special /videos path, since its somehow too dumb and doesnt save it inside the NFS mount, but creates some kind of links

Mind the "docker exec" in the end. It sets ownership to the user 1000 (in this case, the ubuntu user and group). You can probably adapt it to your needs.

**Comment by fryfrog** [comment]
`docker exec -it unifivideo /bin/bash -c "chown -R 1000:1000 /videos` You don't need to do this *in* the container. Having correct permissions is just part of having a correct setup. Do it on the outside *once* and you're done.

**Comment by Beaving** [comment]
Yes, but then I can't just use a new NFS mount which is empty, can't just change folders, can't just recreate everything, without having to manually set the permissions. I want it to plug & play, easier for me :P

**Comment by fryfrog** [comment]
I think this is sorted and I'm closing it.

**Comment by roxlu** [comment]
A bit late, but while looking into a similar problem I stumbled upon this  issue. I wrote an how-to to fix this, might save you same time: https://www.roxlu.com/2019/064/how-to-setup-a-self-hosted-unifi-nvr-with-arch-linux

**Comment by fryfrog** [comment]
Hey, the AUR `unifi-video` package is working for you? I maintain it, but don't *use* it, so that is nice to hear.

**Comment by roxlu** [comment]
yes it works perfectly! thanks
