### ISSUE TITLE
error tmpfs for docker swarm

### ISSUE THREAD

**Issue by Kyosuk3** [pducharme/UniFi-Video-Controller#118]
despite several days of research I can't find a configuration that allows the swarm compose to allow writing to the tmpfs cache.
I have tried the different recommended configurations but swarm denies them:
 security_opt: 
     - apparmor:unconfined 
    cap_add: 
      - SYS_ADMIN  
      - DAC_READ_SEARCH

in the end, I have the following error when the java application starts the binary:
=> mount: /var/cache/unifi-video: permission denied.

I also added a mount tmpfs but that doesn't change anything

**Comment by tmowbrey** [comment]
Anyone able to comment on this thread? I'm having the same issue.

**Comment by fryfrog** [comment]
Does it work fine if you do it the normal, not swarm way?

**Comment by tmowbrey** [comment]
Yes, I've been able to do it the normal way without issue.

**Comment by fryfrog** [comment]
I don't know what that means, is Docker Swarm too old or too new?

Can you use another Docker clustering / management tool? Surely Google can tell you what you should replace security_opt and cap_add with?

**Comment by tmowbrey** [comment]
The [docker compose file provided](https://github.com/pducharme/UniFi-Video-Controller/blob/master/docker-compose.yaml) in the repo is notated as version 3. Version 3 does not support those flags nor does it support anything like them due to security concerns (ultimately that file is non-working). Docker Swarm only supports V3 and higher. 

Almost every unifi video docker image I see requires these flags so I'm not sure that there is actually a solution. Was just hoping someone else may have known otherwise.

**Comment by fryfrog** [comment]
Ah, I've got nothing then. :/

**Comment by tmowbrey** [comment]
Thanks anyways, I really appreciate you taking the time to try to help.

**Comment by x-jokay** [comment]
More information about the problem with missing `cap_add` in docker swarm can be found in this issue https://github.com/moby/moby/issues/25885.

**Comment by fryfrog** [comment]
I'm just gonna close this, sorry it doesn't work in docker swarm. :(

**Comment by tonyskapunk** [comment]
I know this has nothing to do with swarm, but I faced the same issue using [podman](https://github.com/containers/libpod/), I was able to solve it by using:
`--mount type=tmpfs,tmpfs-mode=0700,tmpfs-size=512M,destination=/var/cache/unifi-video`

Just in case someone else using podman faces the same issue, since I got here when googling for the issue.
